# -*- coding: utf-8 -*-
"""python1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_48DYNa1kovOOXnrUVqEIiENlhu9TuX
"""

print('welcome')

word = input()
print(word)

message=input()
print(message)

a=int(input("Enter the integer: "))
print(a)



#print the given fractional number.
fra=20.04
print(fra)

num=20.04567
print("{:.2f}".format(num))

num = 255
print(hex(num),oct(num))

hex_num = "0xFF"
print(int(hex_num, 16))

oct_num = "0o77"
print(int(oct_num, 8))

chr = 'T'
print(ord(chr))

ascii = 65
print(chr(ascii))

n = 10
m = 20
print(n, m)

a = 10
b = 20
print(a, "\t", b)

chr = 'A'
print("'" + chr + "'")

print("\"Hello\" \"World\"")

day = input("Enter day: ")
month = input("Enter month: ")
year = input("Enter year: ")

print(day + "/" + month + "/" + year)

n=int(input("enter number: "))
print("+",n)

import sys
# sys.getsizeof function is used to retrieve the size of each variable.
chr = 'A'
num = 11
f = 15.5
d = 30.54567

print("Size of char:", sys.getsizeof(chr))
print("Size of int:", sys.getsizeof(num))
print("Size of float:", sys.getsizeof(f))
print("Size of double:", sys.getsizeof(d))

roll_no = 321
name = "Josephine"

print("Roll No:", roll_no, ", Name:", name)

print("English : 85")
print("Maths   : 90")
print("Science : 88")
print("Social  : 80")
print("Tamil   : 92")

blood_group = input("Enter your blood group: ")
print("Your blood group is:", blood_group)

from datetime import datetime

curr_time = datetime.now().strftime("%H:%M:%S")
print(curr_time)

from datetime import datetime

curr_time = datetime.now().strftime("%H:%M:%S")
print(curr_time)

print("KIT,\ncoimbatore\nTamil Nadu\nIndia")

from re import M
n=int(input())
m=int(input())
print("addition of 2 numbers:",n+m)
print("Difference of 2 numbers:",n-m)
print("product of 2 numbers:",n*m)
print("remainder of 2 numbers:",n%m)
print("quotient of 2 numbers:",n//m)

#swapping two var using third variable
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

temp = a
a = b
b = temp

print("After swapping:")
print("a =", a)
print("b =", b)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

a = a + b
b = a - b
a = a - b

print("After swapping:")
print("a =", a)
print("b =", b)

#print the last digit of given number N
N = int(input("Enter a number: "))
last_digit = N % 10
print("Last digit of", N, "is", last_digit)

# print the all digits Except last digit of given number n
n = int(input("Enter a number: "))
digit = n // 10
print("All digits of", n, "except last digit:", digit)

# print the middle digit of a 3-digit number.
n = int(input("Enter a 3-digit number: "))
mid_digit = (n % 100) // 10
print("Middle digit of", n, "is", mid_digit)

# print the absolute value of a given number.
n = int(input("Enter a number: "))
abs_value = abs(n)
print("Absolute value of", n, "is", abs_value)

# print the square of a given number
n = int(input("Enter a number: "))
square = n ** 2
print("Square of", n, "is", square)

# print the cube of a given number
n = int(input("Enter a number: "))
cube = n ** 3
print("Cube of", n, "is", cube)

#average of three numbers
a=int(input())
b=int(input())
c=int(input())
print(a+b+c/3)

#equal or not
a=int(input())
b=int(input())
if a==b:
  print("equal")
else:
  print("not equal")

#Program to check if a number is power of 2 using bitwise AND.
num = int(input("Enter a number: "))

if num > 0 and (num & (num - 1)) == 0:
    print("Power of 2")
else:
    print("Not a power of 2")

num = int(input("Enter a number: "))

if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a > b and a > c:
    print("Greatest number is", a)
elif b > c:
    print("Greatest number is", b)
else:
    print("Greatest number is", c)

marks = int(input("Enter marks: "))

if marks >= 35:
    print("Pass")
else:
    print("Fail")

#area of rectangle,square,circle and traingle
#rectangle
l=int(input())
b=int(input())
print("area of rectangle:",l*b)

#square
a=int(input())
print("area of square:",a*a)

#circle
r=int(input())
print("area of circle:",3.14*r*r)

#triangle
b=int(input())
h=int(input())
print

import math

x1 = int(input("Enter x1: "))
y1 = int(input("Enter y1: "))
x2 = int(input("Enter x2: "))
y2 = int(input("Enter y2: "))

distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print("Distance =", distance)

#fahrenheit to celcius
fah=float(input("enter the fahrenheit:"))
cel=(fah-32)*5/9
print(cel)

#celcius to fahrenheit
cel=float(input("enter the celcius:"))
fah=(cel*9/5)+32
print(fah)

#perimeter

#circumference of circle
r=int(input())
print("perimeter of circle:",2*3.14*r)

#rectangle
l=int(input())
b=int(input())
print("perimeter of rectangle:",2*(l+b))

#square
a=int(input("enter the side:"))
print("perimeter of square:",4*a)

6#cubee
#surface area
a=int(input())
print("surface area of cube:",6*a*a)

#volume

print("volume of cube:",a*a*a)

#perimeter
print("perimeter if cube:",12*a)

#cuboid
#surface area
l=int(input())
b=int(input())
h=int(input())
print("surface area of cuboid:",2*(l*b+b*h+l*h))

#volume
print("volume of cuboid:",l*b*h)

#sphere
#surface area
r=int(input())
print("surface area of sphere:",4*3.14*r*r)

#volume
print("volume of sphere:",4/3*3.14*r*r*r)

#cylinder
#surface
r=int(input())
h=int(input())
print("surface area of cylinder:",2*3.14*r*(r+h))

#volume
print("volume of cylinder:",3.14*r*r*h)

#Print Price After Discount
price=float(input("enter the price:"))
discount=float(input("enter the discount:"))
print("price after discount:",price-price*discount/100)

#minutes to seconds
minutes=int(input("enter the minutes:"))
print(minutes*60,"seconds")

bill = int(input("Enter total bill amount: "))

share = bill / 3

print("Each friend should pay =", share)

#calculation of distance travlled
speed=int(input("enter the speed:"))
time=int(input("enter the time:"))
print("distance travlled:",speed*time)

#
char=input()
if char.isdigit():
  print("char is digit")
elif char.isalpha():
  print("char is alphabet")
else:
  print("spl symbol")

number=int(input("enter the number: "))
if number>=0 and number <= 9:
  print("single digit number")
elif number >=10 and number<= 99:
  print("two digit number")
elif number >= 100 and number <= 999:
  print("Three digit number")
else:
  print("More than three digit number")

num=int(input("enter the 4 digit nmber:"))

frst_two=num//100
last_two=num%100

if frst_two==last_two:
  print("frst and last two digits are equal")
else:
  print("not equal")

n=int(input())
match n:
  case i if n>=90:print("A")
  case i if 75 <=n <90:print("B")
  case i if 60<=n<75:print("C")
  case i if  35<=n<60:print("D")
  case _:print("Fail")

#operators
#2
l=int(input())
b=int(input())
perimeter=2*(l+b)
area=l*b
print(area,perimeter)

4